20 rating model
The-Alchemist-Org/alchemist-backend pull request #24
Opened 2024-04-18 09:08 UTC by fiskfisk33

2024-04-18 09:28 UTC, neonguyen-dev requested changes
Kolla igenom om att potentiellt lägga en composite key på recipe_id och user_id istället för en PK på id som inkrementerar så att det inte är möjligt att lägga till mer än 1 rating på ett recept som en användare.

2024-04-18 09:28 UTC, neonguyen-dev commented on src/database/migrations/1713430057593-RatingModel.ts
> +        	await queryRunner.dropTable('queues');
```suggestion
        	await queryRunner.dropTable('ratings');
```

2024-04-18 09:28 UTC, neonguyen-dev commented on src/database/migrations/1713430057593-RatingModel.ts
> +					//Should include serial number as a foreign key constraint whenever that is setup
```suggestion					
```

2024-04-18 09:28 UTC, neonguyen-dev commented on src/database/migrations/1713430057593-RatingModel.ts
> +import { MigrationInterface, QueryRunner, Table } from "typeorm";
```suggestion
import { MigrationInterface, QueryRunner, Table } from 'typeorm';
```

2024-04-18 09:32 UTC, fiskfisk33 commented on src/database/migrations/1713430057593-RatingModel.ts
> +        	await queryRunner.dropTable('queues');
oops... hah

2024-04-20 11:25 UTC, D3nnis38 requested changes
Se till att du har ESLint installerat på din code-editor och att auto formateraren är inställd på ES-lint så indentaion blir korrekt

2024-04-24 07:09 UTC, fiskfisk33 commented
så, nu borde det vara korrekt enligt eslint :)

2024-04-24 11:11 UTC, neonguyen-dev approved these changes
LGTM som en första draft på Rating Model

2024-04-30 08:34 UTC, D3nnis38 approved these changes

2024-04-30 09:02 UTC, merged